### ISSUE TITLE
"No state file was found" on initial Observe of Inline workspace

### ISSUE THREAD

**Issue by AaronME** [crossplane-contrib/provider-terraform#119]
### What happened?
We created Workspace with an inline manifest. When deploying Workspace, it failed sync or become ready. The status field showed:
```
      message: "observe failed: cannot list Terraform resources: \e[31mno state file
        was found!"
      reason: ReconcileError
      status: "False"
      type: Synced
```

### How can we reproduce it?
1. Create a Workspace with inline manifest.
1. Deploy to a cluster with provider-terraform installed
1. Resource never syncs.

We could only get a successful `apply` by manually creating a "terraform.tfstate" file within the running container under the Workspace's `terraform.tfstate.d/<workspace>/` folder.

### What environment did it happen in?
Crossplane version: UXP v1.9.0-up.3
provider-terraform version: 0.4.0

**Comment by bobh66** [comment]
@AaronME - did you configure a terraform backend, either inline or in a ProviderConfig - https://github.com/crossplane-contrib/provider-terraform/blob/master/examples/providerconfig.yaml#L27 ?

**Comment by AaronME** [comment]
Thanks @bobh66 ! That worked.
