### ISSUE TITLE
self-signed certificate for terraform remote

### ISSUE THREAD

**Issue by ripro-patrick** [crossplane-contrib/provider-terraform#161]
I am currently trying to implement crossplane provider terraform into a custom environment at a customer.
Sadly, there seems to be no way to inject certificates for the "remote" connection of the terraform workspace.

according to the current documentation, I did not find any reference how a custom trust store might be specified.

Can you please extend the functionality so that the trust store can be updated to include the required CAs in order to get rid of the error message?

error message:
```
Status:
  At Provider:
    Outputs:
      Token:  mytoken
      URL:    url...
  Conditions:
    Last Transition Time:  2023-02-10T12:49:56Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2023-02-10T12:50:00Z
    Message:               connect failed: cannot get remote Terraform module: error downloading '[https://***/scm/cloud/crossplane-test.git':](https://%2A%2A%2A/scm/cloud/crossplane-test.git':)
Get [https://***/scm/cloud/crossplane-test.git?terraform-get=1](https://%2A%2A%2A/scm/cloud/crossplane-test.git?terraform-get=1): x509: certificate signed by unknown authority
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason                   Age                 From                                Message
  ----     ------                   ----                ----                                -------
  Warning  CannotConnectToProvider  79s (x65 over 63m)  managed/[workspace.tf.crossplane.io](http://workspace.tf.crossplane.io/)  cannot get remote Terraform module: error downloading 'htt
ps://***/scm/cloud/crossplane-test.git': Get [https://***/scm/cloud/crossplane-test.git?terraform-get=1](https://%2A%2A%2A/scm/cloud/crossplane-test.git?terraform-get=1): x509: certificate signed b
y unknown authority
```

**Comment by bobh66** [comment]
@hasheddan - would the proposed PRI changes provide a way to inject custom cert chains into provider pods to handle situations like this?

**Comment by ytsarev** [comment]
Please see related discussion https://github.com/crossplane/crossplane/discussions/2777 . Back in the days, I had to build custom provider image to handle similar situation.

**Comment by ripro-patrick** [comment]
@ytsarev 
Thanks a lot, your hint helped me to solve the issue.
I extended the container image to include the required certificates and successfully extended it with other features (e.g. the terraform container can't run any azurerm modules in terraform as there is no cli available in the container.
It would be appreciated to get the functionality without the need to create a custom image tough (there are certainly better ways to do that)
