### ISSUE TITLE
[Question] Does provider-terraform support reconciliation for drifts auto-detecting against target system

### ISSUE THREAD

**Issue by morningspace** [crossplane-contrib/provider-terraform#18]
I was looking at provider-terraform and basically it looks to me that’s a wrapper of Terraform CLI. However, correct me if I’m wrong, the way that we wrap Terraform will not gain the reconciliation benefit natively as other Kubernetes native providers do. Is it right?

Say, I have some Terraform assets wrapped using a provider and exposed as XRs, it will help me drive the Terraform automation via Crossplane, but when I modify something on target system where the Terraform automation is applied by the provider, Crossplane won’t help me auto-detect the drifts unless I add some specific code in provider  (maybe in Observe?) to selectively pick up some status to check against the target system then react correspondingly. But given that’s the generic provider, I will not be able to inject such specific code logic in it.

**Comment by negz** [comment]
@morningspace This provider will detect and automatically correct drift. It invokes Terraform every 60 seconds, uses `terraform plan` to determine whether there is drift, then uses `terraform apply` to correct the drift. Does that make sense?

**Comment by morningspace** [comment]
Thanks @negz, that makes sense!
