### ISSUE TITLE
Workspace fails on Warning event type

### ISSUE THREAD

**Issue by ytsarev** [crossplane-contrib/provider-terraform#20]
### What happened?

Workspace fails with
```
Events:
  Type     Reason                         Age                 From                                Message
  ----     ------                         ----                ----                                -------
  Warning  CannotObserveExternalResource  32s (x16 over 10m)  managed/workspace.tf.crossplane.io  cannot diff (i.e. plan) Terraform configuration: value for undeclared variable
```

As it is a Warning it should be probably purely informative. 

Also, the output is apparently suppressed as standard terraform output should provide some hints on which variable it is similar to

```
Warning: Value for undeclared variable

  on /Users/ekini/project_dir/preview/service-app/../env.tfvars line 11:
  11: ecs_service_container_prot   = 8000

The root module does not declare a variable named
"ecs_service_container_prot". Did you mean one of
[ecs_service_container_port]?
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### How can we reproduce it?
Declare the value for variable that is not mentioned in tf module configuration
```
    vars:
    - key: undeclared-var
      value: bar
```

**Comment by negz** [comment]
> As it is a Warning it should be probably purely informative.

There's only two types of Kubernetes event - `Normal` and `Warning`. So despite "warning" typically having a different meaning to "error" when it comes to log levels, it's not quite the same here. "Warning" just means "something bad happened".

**Comment by ytsarev** [comment]
So Warning here is actually fine but additional context is hard to retrieve. We should eventually solve it in https://github.com/crossplane-contrib/provider-terraform/issues/61
