### ISSUE TITLE
Provider leaves terraform state Secrets and Leases behind

### ISSUE THREAD

**Issue by bobh66** [crossplane-contrib/provider-terraform#40]
### What happened?
When using the terraform provider with the kubernetes backend, the state Secrets and Leases that terraform creates get left behind after the Workspace object is deleted.

### How can we reproduce it?
Create a Workspace object that uses the kubernetes back end.  Observe that a Secret and Lease gets created in the designated namespace.

Delete the object and observe that the Secret and Lease remains.

### What environment did it happen in?
Crossplane version: 1.7

While there may be scenarios where the Secret and Lease need to be retained after deletion, I think it's more likely that when the Workspace gets deleted the Secret and Lease can also be deleted.

Maybe a configuration option should be used to determine whether or not the Secret/Lease gets deleted?

I can think of several possible implementations:

- after the tf.Apply() call in the Update method, query for any Secrets/Leases with the label "tfstate: true" and "tfStateWorkspace" = workspace_name and set the OwnerReference in the Secret and Lease to point at the Workspace, so the Secret/Lease would get deleted when the Workspace gets deleted.  One possible drawback is that this code would get re-executed any time there is a difference in the terraform plan output

- in the Delete() method run the same query for Secrets/Leases with the  "tfstate: true" and tfStateWorkspace label and delete them

- update the Garbage Collection code to scan for Secrets and Leases that are associated with Workspaces that don't exist anymore and remove them

- run a watcher for the creation of new Secret and Lease objects and make the Workspace the Owner of the Lease and Secret, so they will get deleted along with the Workspace

@ytsarev - any other ideas?

**Comment by bobh66** [comment]
A sample of the many Secrets that are orphaned by the provider:

```
apiVersion: v1
data:
  tfstate: <base64 data>
kind: Secret
metadata:
  annotations:
    encoding: gzip
  creationTimestamp: "2022-04-03T17:03:40Z"
  labels:
    app.kubernetes.io/managed-by: terraform
    tfstate: "true"
    tfstateSecretSuffix: xp
    tfstateWorkspace: bobtest-qclds-vcxqb
  name: tfstate-bobtest-qclds-vcxqb-xp
  namespace: crossplane-system
  resourceVersion: "610635692"
  selfLink: /api/v1/namespaces/crossplane-system/secrets/tfstate-bobtest-qclds-vcxqb-xp
  uid: 916436f2-718d-4539-a890-252faf32d93c
type: Opaque
```

The tfstate, tfstateSecretSuffix and tfStateWorkspace labels are all added by the Terraform k8s backend.  The only link between this Secret and the Workspace object is the tfstateWorkspace label.   Unfortunately terraform doesn't have an easy way to "inspect" the configuration so you can't tell that the kubernetes backend is in use without querying for the Secret by the labels above.

The Secret cannot be deleted until the tf.Destroy() has finished.

Once the Workspace is deleted there is no way for the provider-terraform code to know that the Secret is eligible for Garbage Collection.  The Workspace GC code has a list of valid Workspaces, so it would be possible to list all Secrets with the tfstate: true label and remove any that don't have valid tfstateWorkspace values.  In this solution I think I would query for the Secrets before the Workspaces so that the GC code doesn't delete "new" Secrets that might get created after the Workspace list is executed but before the Secrets list is complete.

**Comment by bobh66** [comment]
Here is one possible implementation using the existing Garbage Collection routine:

1 - Collect the current list of Secrets and Leases that have the Label "tfstate" = "true".  Do this before the list of Workspaces is retrieved to minimize race conditions
```
        // Look for label tfstate = "true"
        labels := map[string]string{"tfstate": "true"}
        sl := &corev1.SecretList{}
        _ = gc.kube.List(ctx, sl, client.MatchingLabels(labels))
        ll := &coordv1.LeaseList{}
        _ = gc.kube.List(ctx, ll, client.MatchingLabels(labels))
```
2 - create a second map[string]bool that uses the workspace name as the key and populate it along with the current "exists" map

3 - Scan the lists of Secrets and Leases for workspace names in the tfStateWorkspace label that do not exist in the new name map and delete those Secrets/Leases

```
func (gc *GarbageCollector) collectLeases(ctx context.Context, ll *coordv1.LeaseList, wse map[string]bool) {
        for i := range ll.Items {
                l := ll.Items[i]
                wsn := l.Labels["tfstateWorkspace"]
                if wsn != "" {
                        _, le := wse[wsn]
                        if !le {
                                _ = gc.kube.Delete(ctx, &l)
                        }
                }
        }
}

func (gc *GarbageCollector) collectSecrets(ctx context.Context, sl *corev1.SecretList, wse map[string]bool) {
        for i := range sl.Items {
                l := sl.Items[i]
                wsn := l.Labels["tfstateWorkspace"]
                if wsn != "" {
                        _, le := wse[wsn]
                        if !le {
                                _ = gc.kube.Delete(ctx, &l)
                        }
                }
        }
}
```

I'm sure there is a way to do this in one function instead of 2 but my go skills are not up to that level of abstraction yet.

@ytsarev Please let me know what you think.  Thanks!

**Comment by ytsarev** [comment]
Hi @bobh66, apologies for the long response on this one, and thanks a ton for drafting the implementation proposal, I really appreciate it!

Before implementing GC based solution I would try to extend [Destroy](https://github.com/crossplane-contrib/provider-terraform/blob/master/internal/terraform/terraform.go#L418) or [Delete](https://github.com/crossplane-contrib/provider-terraform/blob/master/internal/controller/workspace/workspace.go#L314) methods with the logic similar to the one you provided above but using the reference of `tfstateWorkspace: $workspace_name` label.  So it will be directly cleaned up during the resource finalization process.

Another important point to discuss is how we detect that the terraform workspace is actually using Kubernetes backend, it can be any other arbitrary backend depending on the configuration block of ProviderConfig.

**Comment by bobh66** [comment]
Thanks @ytsarev.

Ideally there would be a terraform CLI command that would display the backend configuration but I haven't found one.

If the terraform module is specified Inline we could detect a kubernetes backend by searching for the pattern 'backend "kubernetes" in the module string'.  If the source is remote then we would need to search all of the files in the module source directory after it is fetched.  It _should_ be in a main,tf file but could be in any .tf or .tf.json file.

I was thinking that initially we could assume a kubernetes backend and on Delete search for Secrets/Labels with the appropriate labels, and delete them if they are found.  The workspace name is unique enough that if there is a Secret and/or Label with the tfstateWorkspace label, it would be pretty unlikely to be associated with something else.

Something like:
```
// Destroy() has completed successfully so look for Secrets/Leases with the labels tfstate = "true" and
// tfstateWorkspace = <this workspace name>
labels := map[string]string{"tfstate": "true", "tfstateWorkspace": cr.Name}
sl := &corev1.SecretList{}
_ = gc.kube.List(ctx, sl, client.MatchingLabels(labels))
ll := &coordv1.LeaseList{}
_ = gc.kube.List(ctx, ll, client.MatchingLabels(labels))
```

Then loop through and delete the Items in both lists, which should only be one of each

If there aren't any secrets/leases that match the labels then there is probably a remote backend like S3 that is out of our control.

If you agree I can put it in a PR for further review and testing.

Thanks!

**Comment by bobh66** [comment]
@ytsarev - so the fix I put in for this turned out to be less than ideal.   While it does clean up the Secret and Lease, it leaves behind the environment file in the .terraform directory, so the next time terraform init gets called in Connect(), it fails to find the workspace specified in the environment file, and prompts for the user to select a workspace, which obviously doesn't work.

I don't think we can clean up the Secret/Lease in Delete() because the reconciliation loop is going to call Observe() again after Delete() is called and we need the terraform workspace (the Secret/Lease)  to still exist.

I think the correct way to do this is to have GC call terraform workspace delete <workspace> which will clean up the Secret and Lease.   I'll open another issue/PR and test this change.
