### ISSUE TITLE
Not getting healthy status of terraform provider

### ISSUE THREAD

**Issue by vinokumark** [crossplane-contrib/provider-terraform#64]
After deployed the terraform provider not showing healthy. Also the provider config for terraform not working.

**Comment by bobh66** [comment]
Can you run describe on the provider and see what it says?  Are there any useful logs in the provider pod?

**Comment by ytsarev** [comment]
Looks like some temporary installation issue? @vinokumark please reopen if it still happens and we will try to debug together.
