### ISSUE TITLE
Expose git credentials for inline as well as remote module sources

### ISSUE THREAD

**Issue by bobh66** [crossplane-contrib/provider-terraform#74]
### What happened?
We used an Inline module that had a remote module defined within it and the git credentials in the provider config are not exposed in the GIT_CRED_DIR

### How can we reproduce it?
Define an "inline" module workspace that contains a module which pulls source from a remote git repository.  Make sure that the providerconfig has a .git-credentials entry

terraform init will fail because the git credentials are not available to terraform without the GIT_CRED_DIR env var which is only set for remote module source

### What environment did it happen in?
Crossplane version: 1.8.1

**Comment by luisdavim** [comment]
Any changes of getting a version of the controller including this released??

**Comment by ytsarev** [comment]
@luisdavim we can plan a release this week if it is required.

@bobh66 please let me know if you want to drive it so we make you familiar with the process.

**Comment by luisdavim** [comment]
Awesome, thanks 😊

**Comment by ytsarev** [comment]
@luisdavim just to keep you updated, we agreed to release early next week to include https://github.com/crossplane-contrib/provider-terraform/pull/58 into release

**Comment by luisdavim** [comment]
Thanks, I appreciate that 😁
