### ISSUE TITLE
problem using modules with a relative path

### ISSUE THREAD

**Issue by williamchitto** [crossplane-contrib/provider-terraform#83]
We found a problem using modules with a relative path in the workspace remote like this.

module "db_option_group" {
  source = "../db_option_group"

When try to install we get this error \:

2022-08-16T21:03:15.466Z DEBUG controller-runtime.manager.events Warning {"object": {"kind":"Workspace","name":"rds-remote","uid":"62c9fe78-b7df-4796-9eba-ba9700f271dd","apiVersion":"tf.crossplane.io/v1alpha1","resourceVersion":"18459415"}, "reason": "CannotConnectToProvider", "message": "cannot initialize Terraform configuration: unreadable module directory"}

We saw  is made a change to don't use --from-module on previous release, but It seen don't working

What environment did it happen in?
Crossplane version: last version

Cloud provider: AWS
Kubernetes version: v1.21.12
Kubernetes distribution:  EKS
OS VERSION: 18.04.6 LTS (Bionic Beaver)
Kernel: Linux runway-devenv 4.15.0-176-generic #185-Ubuntu SMP Tue Mar 29 17:40:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ytsarev** [comment]
That's well known ( though maybe not documented). The terraform modules that are supposed to work in a distributed scenario like provider-terraform should not sure relative path for the modules. You need to update them to use remote URLs , ideally git https://www.terraform.io/language/modules/sources#generic-git-repository

**Comment by andrecastro** [comment]
@ytsarev could you elaborate a little bit more why it should not be supported? This architecture is working pretty fine with other tools like terragrunt which we point to the root module using the remote git URL and path to the module and this root module call other modules within its repository using relative path.

I thought the issue with this provider was because you're using the `-from-module` flag which I know that does not support it. But I noticed you changed to use go-getter to download the module and do a terraform init on it. So why it does not work? What am I missing here?

Here is an example of our repository structure:

```
.
├── CHANGELOG.md
├── Makefile
├── README.md
├── azure.yaml
├── examples
│   ├── create-rds
│   ├── create-rds-aurora-cluster
│   ├── create-rds-aurora-cluster-with-secrets-manager
│   ├── create-rds-read-replica
│   └── create-rds-subnet-group
├── modules
│   ├── db_option_group
│   ├── generate-rds-secret
│   ├── rds
│   ├── rds-aurora
│   ├── rds-create-subnet-group
│   ├── rds-iam-roles
│   ├── rds-monitoring-role
│   ├── rds-s3-backup
│   ├── rds-s3-integration
│   └── rds-with-secret-manager
├── resources
│   ├── README.md
│   ├── provisioning-policy
│   └── terraform-docs
└── test
    ├── README.md
    ├── aws_rds_test.go
    ├── create_rds_aurora_cluster_test.go
    ├── create_rds_aurora_cluster_with_secrets_manager_test.go
    ├── go.mod
    ├── main_test.go
    └── rds_subnet_group_test.go
```

Usually we do something like: 

source = "git::ssh://git@<ghe-enterprize-url>/runway/terraform-aws-rds.git//modules/rds?ref=v1.0.2"

and within the rds module we call other module both remote and relative...and this works fine.

**Comment by ytsarev** [comment]
@andrecastro 

Sure, so when you are doing something like

```
    source: Remote
    module: git::ssh://git@/runway/terraform-aws-rds.git//modules/rds?ref=v1.0.2
```

It will create Workspace with everything under `/modules/rds` and outlying `../ db_option_group` simply does not exist and is not accessible. 

IIUC that's how `go-getter` works and it is expected behavior, see https://github.com/hashicorp/go-getter#subdirectories

**Comment by jond3k** [comment]
👍  

@ytsarev I also use the 'repo of modules' pattern often with TF and TG

It looks like the Terraform code is full of caveats [here](https://github.com/hashicorp/terraform/blob/4fb8a5a3ec717864f0284b7ea3a1aa2b43df91f6/internal/getmodules/getter.go#L21-L29), [here](https://github.com/hashicorp/terraform/blob/64635edfb9650dbac0e6c63c09588578573bf206/internal/getmodules/installer.go#L38-L41) and [here](https://github.com/hashicorp/terraform/blob/036db86c1fc7f64bc03ff75150e50456b28c9f2b/internal/getmodules/installer.go#L11-L12) with go-getter but a trace confirms that TF asks gogetter to check out the full repo


1. `main.tf`
```
module "my_mod" {
  source = "git@github.com:terraform-google-modules/terraform-google-project-factory.git//modules/project_services/?ref=v13.1.0"
}
```

2. run `TF_LOG=TRACE terraform init` (See `getmodules` line in particular)

```
2022-08-23T23:33:03.724+0100 [TRACE] ModuleInstaller: my_mod is not yet installed
2022-08-23T23:33:03.724+0100 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/my_mod prior to install of my_mod
2022-08-23T23:33:03.724+0100 [TRACE] ModuleInstaller: my_mod address "git::ssh://git@github.com/terraform-google-modules/terraform-google-project-factory.git?ref=v13.1.0//modules/project_services" will be handled by go-getter
Downloading git::ssh://git@github.com/terraform-google-modules/terraform-google-project-factory.git?ref=v13.1.0 for my_mod...
2022-08-23T23:33:03.724+0100 [TRACE] getmodules: fetching "git::ssh://git@github.com/terraform-google-modules/terraform-google-project-factory.git?ref=v13.1.0" to ".terraform/modules/my_mod"
2022-08-23T23:33:06.797+0100 [TRACE] ModuleInstaller: my_mod "git::ssh://git@github.com/terraform-google-modules/terraform-google-project-factory.git?ref=v13.1.0//modules/project_services" was downloaded to .terraform/modules/my_mod/modules/project_services
2022-08-23T23:33:06.808+0100 [DEBUG] Module installer: my_mod installed at .terraform/modules/my_mod/modules/project_services
```

3. init folder confirms that it checks out the full repo

```
ls -l .terraform/modules/my_mod/modules

app_engine
budget
core_project_factory
essential_contacts
fabric-project
gsuite_enabled
gsuite_group
project_services
quota_manager
shared_vpc_access
svpc_service_project
```

**Comment by ytsarev** [comment]
@jond3k good investigation, thanks! I'm trying to wrap my head around it and still can't see a relative path case in your example. Specifically `project_services` does not reference any modules outside, so why do we need to checkout other modules in this case?

**Comment by jond3k** [comment]
@ytsarev it would work with a relative path because `go-getter` is given the entire repo according to this comment (and confirmed by the trace). Where it does the parsing must be further down the stack.

```
// PackageFetcher only works with entire packages. If the caller is processing
// a module source address which includes a subdirectory portion then the
// caller must resolve that itself, possibly with the help of the
// getmodules.SplitPackageSubdir and getmodules.ExpandSubdirGlobs functions.
func (f *PackageFetcher) FetchPackage(ctx context.Context, instDir string, packageAddr string) error {
	return f.getter.getWithGoGetter(ctx, instDir, packageAddr)
}
```

**Comment by ytsarev** [comment]
So what is the overall ask here? provider-terraform should mimic terraform CLI behavior?

**Comment by williamchitto** [comment]
If it is possible to mimic terraform CLI behavio for my problem it would be wonderful

**Comment by andrecastro** [comment]
Mimic terraform CLI for my problem would also be great! We can't and don't want to change all our modules, we are evaluating k8s controllers to work right away with terraform modules and this issue is the only thing that hold us back to use this provider today.

**Comment by bobh66** [comment]
Looking at the go-getter code, the issues seem to be here:  https://github.com/hashicorp/go-getter/blob/main/client.go#L132  and here:  https://github.com/hashicorp/go-getter/blob/main/client.go#L329 - it detects the presence of a submodule, retrieves the whole repo, and then copies over just the siubmodule without the rest of the repo.   I suspect that terraform jumps through some hoops to make it work the way it does, like maybe removing the submodule before it calls Get() and then putting it back before it uses what was retrieved.

**Comment by andrecastro** [comment]
Hey @ytsarev are going to work on this? Do you need help?

**Comment by ytsarev** [comment]
@andrecastro yes, just didn't have the bandwidth to look into it properly yet. I was thinking about it in the background though. Conside this prototype.

```
spec:
  forProvider:
    source: Remote
    module: git::https://github.com/crossplane/tf?ref=main
    entrypoint: sub/directory # '.' by default
```
 Will something like that work? It should enable checking out the whole repo but running tf within a subdirectory of `entrypoint`

**Comment by andrecastro** [comment]
That should work!
Have you tried to look on how terraform and terragrunt solves it? Maybe you could get some ideas from there.

But for us, if you provide us a way to execute it in a sub directory and this sub directory could reference others with relative paths that would be awesome. Thanks!

**Comment by andrecastro** [comment]
hey @ytsarev, how is this going? My team is able to work on it, is there any pointer for contribution?

**Comment by ytsarev** [comment]
@andrecastro I plan to prioritize working on it this week and will be definitely happy to collaborate.

**Comment by ytsarev** [comment]
@andrecastro PR is ready, please test it out if possible 👍  https://github.com/crossplane-contrib/provider-terraform/pull/111

**Comment by andrecastro** [comment]
hey @ytsarev Thank you very much!! 👍 

Is there any way to pull an image version with this change or I need to build it?

**Comment by ytsarev** [comment]
@andrecastro you are very welcome! 

Sure, we have the builds available for `master` branch https://github.com/crossplane-contrib/provider-terraform/actions/runs/3201130360/jobs/5228792912

```
docker.io/crossplanecontrib/provider-terraform:v0.4.0-rc.0.34.g0d8c3da
```

Please keep in mind that we switched to a combined image approach here https://github.com/crossplane-contrib/provider-terraform/pull/112 so there will be no dedicated controller image anymore

Cheers.
